export const testData = {
    storyKor : {
        step1: "일상 속에서 우연히 얻게 된 이상한 돌을 통해, 평범한 사무직 사원 김덕배는 본인도 이해할 수 없는 판타지 세계로 떨어진다.일상 속에서 우연히 얻게 된 이상한 돌을 통해, 평범한 사무직 사원 김덕배는 본인도 이해할 수 없는 판타지 세계로 떨어진다.일상 속에서 우연히 얻게 된 이상한 돌을 통해, 평범한 사무직 사원 김덕배는 본인도 이해할 수 없는 판타지 세계로 떨어진다.일상 속에서 우연히 얻게 된 이상한 돌을 통해, 평범한 사무직 사원 김덕배는 본인도 이해할 수 없는 판타지 세계로 떨어진다.일상 속에서 우연히 얻게 된 이상한 돌을 통해, 평범한 사무직 사원 김덕배는 본인도 이해할 수 없는 판타지 세계로 떨어진다.일상 속에서 우연히 얻게 된 이상한 돌을 통해, 평범한 사무직 사원 김덕배는 본인도 이해할 수 없는 판타지 세계로 떨어진다.일상 속에서 우연히 얻게 된 이상한 돌을 통해, 평범한 사무직 사원 김덕배는 본인도 이해할 수 없는 판타지 세계로 떨어진다.떨어진다.떨어진다.떨어진다.떨어",
        step2: "김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다. 김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명을 결정해야 하는 상황에 직면한다.김덕배는 이 이세계에서 살아남기 위해 스스로의 운명 ",
        step3: "처음에는 이 모험을 두려워하며 거절하려 했지만, 자신의 삶을 위협하는 마법과 몬스터들을 피해 도망다니면서 점점 실력이 늘어난다.처음에는 이 모험을 두려워하며 거절하려 했지만, 자신의 삶을 위협하는 마법과 몬스터들을 피해 도망다니면서 점점 실력이 늘어난다.처음에는 이 모험을 두려워하며 거절하려 했지만, 자신의 삶을 위협하는 마법과 몬스터들을 피해 도망다니면서 점점 실력이 늘어난다.처음에는 이 모험을 두려워하며 거절하려 했지만, 자신의 삶을 위협하는 마법과 몬스터들을 피해 도망다니면서 점점 실력이 늘어난다.처음에는 이 모험을 두려워하며 거절하려 했지만, 자신의 삶을 위협하는 마법과 몬스터들을 피해 도망다니면서 점점 실력이 늘어난다.처음에는 이 모험을 두려워하며 거절하려 했지만, 자신의 삶을 위협하는 마법과 몬스터들을 피해 도망다니면서 점점 실력이 늘어난다.처음에는 이 모험을 두려워하며 거절하려 했지만, 자신의 삶을 위협하는 마법과 몬스터들을 피해 도망다니면서 점점 실력이 늘어난다.어난다",
        step4: "그의 앞에 나타난 김엘프, 동료로서 그에게 생존을 위한 팁과 전투 기술을 가르쳐주며 김덕배가 이세계에서 살아남을 수 있게 돕는다.그의 앞에 나타난 김엘프, 동료로서 그에게 생존을 위한 팁과 전투 기술을 가르쳐주며 김덕배가 이세계에서 살아남을 수 있게 돕는다.그의 앞에 나타난 김엘프, 동료로서 그에게 생존을 위한 팁과 전투 기술을 가르쳐주며 김덕배가 이세계에서 살아남을 수 있게 돕는다.그의 앞에 나타난 김엘프, 동료로서 그에게 생존을 위한 팁과 전투 기술을 가르쳐주며 김덕배가 이세계에서 살아남을 수 있게 돕는다.그의 앞에 나타난 김엘프, 동료로서 그에게 생존을 위한 팁과 전투 기술을 가르쳐주며 김덕배가 이세계에서 살아남을 수 있게 돕는다.그의 앞에 나타난 김엘프, 동료로서 그에게 생존을 위한 팁과 전투 기술을 가르쳐주며 김덕배가 이세계에서 살아남을 수 있게 돕는다.그의 앞에 나타난 김엘프, 동료로서 그에게 생존을 위한 팁과 전투 기술을 가르쳐주며 김덕배가 이세계에서 살아남을 수 있게게",
        step5: "그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고 이곳에서 살아가기로 결정한다.그런 과정 속에서 김덕배는 이세계에서의 삶을 받아들이고",
        step6: "김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할을 부담하게 된다.김덕배는 카이져라는 이름의 마왕과 그의 추종자들로부터 이세계를 지키는 역할",
        step7: "마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.마왕 카이져와 그의 수하들과의 큰 전투에서 김덕배는 직면하게 되고, 처음에는 밀리며 절망에 빠진다.에 빠진다",
        step8: "김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고통을 받는다.김덕배는 이세계의 동료들과의 연결을 잃고, 많은 상처와 고",
        step9: "하지만 그는 다시 일어나 이세계에서 배운 능력과 지식, 그리고 친구들에 대한 사랑을 바탕으로 다시 한 번 마왕과 맞서 싸우기로 결심한다.하지만 그는 다시 일어나 이세계에서 배운 능력과 지식, 그리고 친구들에 대한 사랑을 바탕으로 다시 한 번 마왕과 맞서 싸우기로 결심한다.하지만 그는 다시 일어나 이세계에서 배운 능력과 지식, 그리고 친구들에 대한 사랑을 바탕으로 다시 한 번 마왕과 맞서 싸우기로 결심한다.하지만 그는 다시 일어나 이세계에서 배운 능력과 지식, 그리고 친구들에 대한 사랑을 바탕으로 다시 한 번 마왕과 맞서 싸우기로 결심한다.하지만 그는 다시 일어나 이세계에서 배운 능력과 지식, 그리고 친구들에 대한 사랑을 바탕으로 다시 한 번 마왕과 맞서 싸우기로 결심한다.하지만 그는 다시 일어나 이세계에서 배운 능력과 지식, 그리고 친구들에 대한 사랑을 바탕으로 다시 한 번 마왕과 맞서 싸우기로 결심한다.하지만 그는 다시 일어나 이세계에서 배운 능력과 지식, 그리고 친구들에 대한 사",
        step10: "결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이져를 물리치고 이세계를 구한다.결국 김덕배는 자신의 능력과 지식을 활용하여 마왕 카이",
        step11: "전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계의 영웅이 되며, 그의 용감함과 결단력을 인정받게 된다.전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계의 영웅이 되며, 그의 용감함과 결단력을 인정받게 된다.전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계의 영웅이 되며, 그의 용감함과 결단력을 인정받게 된다.전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계의 영웅이 되며, 그의 용감함과 결단력을 인정받게 된다.전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계의 영웅이 되며, 그의 용감함과 결단력을 인정받게 된다.전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계의 영웅이 되며, 그의 용감함과 결단력을 인정받게 된다.전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계의 영웅이 되며, 그의 용감함과 결단력을 인정받게 된다.전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계의 영웅이 되며, 그의 용감함과 결단력을 인정받게 된다.전투 후, 김덕배는 마왕 카이져로부터 해방된 이세계",
        step12: "김덕배는 다시 일상의 세상으로 돌아가지 못하지만, 이세계에서의 삶을 행복하게 살아가며, 이세계에서의 두 번째 일상을 즐기게 된다.김덕배는 다시 일상의 세상으로 돌아가지 못하지만, 이세계에서의 삶을 행복하게 살아가며, 이세계에서의 두 번째 일상을 즐기게 된다.김덕배는 다시 일상의 세상으로 돌아가지 못하지만, 이세계에서의 삶을 행복하게 살아가며, 이세계에서의 두 번째 일상을 즐기게 된다.김덕배는 다시 일상의 세상으로 돌아가지 못하지만, 이세계에서의 삶을 행복하게 살아가며, 이세계에서의 두 번째 일상을 즐기게 된다.김덕배는 다시 일상의 세상으로 돌아가지 못하지만, 이세계에서의 삶을 행복하게 살아가며, 이세계에서의 두 번째 일상을 즐기게 된다.김덕배는 다시 일상의 세상으로 돌아가지 못하지만, 이세계에서의 삶을 행복하게 살아가며, 이세계에서의 두 번째 일상을 즐기게 된다.김덕배는 다시 일상의 세상으로 돌아가지 못하지만, 이세계에서의 삶을 행복하게 살아가며, 이세계에서의 두 번째 일상을 즐기게",
    },
    storyEng : {
        step1: "Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentally finds in his daily life.Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentally finds in his daily life.Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentally finds in his daily life.Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentally finds in his daily life.Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentally finds in his daily life.Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentally finds in his daily life.Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentally finds in his daily life.Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentally finds in his daily life.Deokbae Kim, an ordinary white-collar worker, falls into a fantasy world that even he cannot comprehend, through a strange stone he accidentallyhehe",
        step2: "Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where he has to decide his own destiny in order to survive in this world.Deok-bae Kim is faced with a situation where",
        step3: "At first, he was afraid of this adventure and tried to refuse it, but his skills gradually improved as he ran away from magic and monsters that threatened his life.At first, he was afraid of this adventure and tried to refuse it, but his skills gradually improved as he ran away from magic and monsters that threatened his life.At first, he was afraid of this adventure and tried to refuse it, but his skills gradually improved as he ran away from magic and monsters that threatened his life.At first, he was afraid of this adventure and tried to refuse it, but his skills gradually improved as he ran away from magic and monsters that threatened his life.At first, he was afraid of this adventure and tried to refuse it, but his skills gradually improved as he ran away from magic and monsters that threatened his life.At first, he was afraid of this adventure and tried to refuse it, but his skills gradually improved as he ran away from magic and monsters that threatened his life.At first, he was afraid of this adventure and tried to refuse it, but his skills gradually improved as he ran away from magic and monsters that threatened his life.At first, he was afraid of this adventure and tried to refuse it, but his skills gradually improved as he ran away from magic and monsters that threatened his life.and monsters that threatened his life.and monsters that threatened his life.and monsters that threatened his life.and monsters that threatened his life.and monsters that threatened his lif",
        step4: "Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf, who appears in front of him, teaches him survival tips and combat skills as a colleague and helps Kim Deok-bae survive in a different world.Kim Elf,lf",
        step5: "In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another world and decides to live there.In that process, Deokbae Kim accepts life in another wo",
        step6: "Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his followers.Kim Deok-bae will take on the role of protecting the other world from the demon king named Kaiser and his fo",
        step7: "Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok-bae Kim is faced with a great battle with Kaiser the Demon King and his men, and at first he is pushed back and falls into despair.Deok",
        step8: "Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim loses connection with his colleagues in the other world and suffers a lot of wounds and pain.Deok-bae Kim los",
        step9: "However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in another world and his love for his friends.However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in another world and his love for his friends.However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in another world and his love for his friends.However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in another world and his love for his friends.However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in another world and his love for his friends.However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in another world and his love for his friends.However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in another world and his love for his friends.However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in another world and his love for his friends.However, he rises again and decides to fight against the demon king once again based on the ability and knowledge he learned in anot",
        step10: "In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In the end, Deok-bae Kim uses his abilities and knowledge to defeat the Demon King Kaiser and save the other world.In th",
        step11: "After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim becomes a hero in another world freed from Kaiser, the Demon King, and his courage and determination are recognized.After the battle, Deok-bae Kim",
        step12: "Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life in another world.Deok-bae Kim cannot return to the everyday world, but he lives happily in another world and enjoys his second daily life",
    },
    imageUrl : {
        step1: {
            name : "1.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/ac758adf-b652-4ef3-bed2-0da2d835ed3a.png"
        },
        step2: {
            name : "2.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/4600cd8c-5f21-40eb-b9d7-74a7d642b34b.png"
        },
        step3: {
            name : "3.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/74c9f092-043c-40c2-a079-7bae10b4614f.png"
        },
        step4: {
            name : "4.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/9c5605b8-2aad-4969-969b-2d89de9bad2c.png"
        },
        step5: {
            name : "5.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/cedd382e-a6a5-4c75-9d1a-23e945285bcf.png"
        },
        step6: {
            name : "6.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/adada819-e16c-493a-80ce-a0e0b53c738c.png"
        },
        step7: {
            name : "7.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/7d9c9c7f-090f-40ec-8246-08eaac9581df.png"
        },
        step8: {
            name : "8.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/08c42fb6-5cd6-4952-aa50-7f0780de3ee0.png"
        },
        step9: {
            name : "9.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/daa2fc59-3a59-48a9-8bab-f88f5f4c0a0b.png"
        },
        step10: {
            name : "10.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/0e12713e-905a-45c8-9768-5faad4e886d3.png"
        },
        step11: {
            name : "11.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/fcccbf4e-6bfe-4815-9497-1b2319d04762.png"
        },
        step12: {
            name : "12.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230809/dd4051a4-9816-47b2-ade0-cbf4eb9ce255.png"
        },
    },

    cover: {
        imageUrl: {
            name : "cover.png",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/banner/20230810/829d1a7c-3d66-4d5b-8cb5-c6ff71ad9c72.png"
        },
        text: "Deok-bae Kim, a worker in a different world"
    },

    lastPage: {
        comment1: "오펜하이머의 이상주의가 그를 곤경에 빠지게 했을 때, 나는 그것이 우리가 받은 훌륭한 윤리학 교육의 논리적인 귀결이라고 느꼈다. 펠릭스 애들러와 존 러브조이 엘리엇의 학생이라면 아무리 현명하지 못한 선택일지라도 자신의 양심에 따라 행동할 것이었다.-데이지 뉴먼(에티컬 컬처 스쿨 동급생)",
        comment2: "나는 오펜하이머를 만나자마자 대단한 재능을 타고난 사람이라는 것을 알 수 있었습니다.-막스 보른",
        comment3: "스페인 문제에 대해서는 충분히 할 만큼 했다. 세상에는 다른 더 급박한 위기가 닥치고 있다.-로버트 오펜하이머",
        character: {
            name: "🐤",
            path: "https://clova-practice.codingbiz.creverse.com/api/file/icon/20230816/6110d5ad-d926-4f49-9c36-1b65b271a57c.png"
        },
        nickName: "김작가호랭작가"
    },

    description: "일반인 김덕배의 좌충우돌 판타지 모험 이야기. 평범한 일상 속 햄스터 챗바퀴 돌리듯 휩쓸려 살기만하는 일상 속에서 모험을 꿈꾸는가? 여기에 바로 용사 김덕배의 이야기가 있다."
}